name: Build and Release Windows

on:
  workflow_dispatch:
  push:
    branches: 
      - "main"
    tags:
      - "v*"
  
jobs:
  build_win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: build
        run: cargo b -r

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            ./target/release/lwd-warp.exe
            ./target/release/zcash-warp.exe
